# usrgrp-manager keybindings
# Format: Action = KeySpec
Quit = q
Ignore = Esc
OpenFilterMenu = f
OpenHelp = ?
StartSearch = /
NewUser = n
DeleteSelection = Delete
SwitchTab = Tab
ToggleUsersFocus = BackTab
ToggleKeybindsPane = Shift+K
EnterAction = Enter
MoveUp = Up
MoveDown = Down
MoveLeftPage = Left
MoveRightPage = Right
PageUp = PageUp
PageDown = PageDown
